### ISSUE TITLE
Global is now a solidity directive

### ISSUE THREAD

**Issue by sambacha** [OpenZeppelin/solidity-ast#21]
New 'Global' directive 

from the documentation:

> When the directive is used at file level and applied to a
> user-defined type which was defined at file level in the same file,
> the word ``global`` can be added at the end. This will have the
> effect that the functions are attached to the type everywhere
> the type is available (including other files), not only in the
> scope of the using statement.

This is similar to `Error`, `Revert` and `From` in that they are not 'real' keywords

**Comment by frangio** [comment]
Thanks @sambacha! :hugs: Fixed in dcb8c63 along with a few other new Solidity features in 0b787828.
