### ISSUE TITLE
Add `documentation` to `StructDefinition` type

### ISSUE THREAD

**Issue by ericglau** [OpenZeppelin/solidity-ast#30]
Since Solidity v0.8.20, the AST can include annotations in a `documentation` section in `StructDefinition`.

Add `documentation` to the `StructDefinition` type.

Example usage:
```
       if (node.documentation?.text.startsWith('@custom:storage-location')) {
```
This currently gives an error:
```
Property 'documentation' does not exist on type 'StructDefinition'.
```

**Comment by frangio** [comment]
Fixed in https://github.com/OpenZeppelin/solidity-ast/commit/81b14e753f6a509c2b6c854c595929f324535331 and released in v0.4.50.
