### ISSUE TITLE
BUG: Wrong SRC when dealing with a solidity file that contain ASCII art

### ISSUE THREAD

**Issue by he110-1** [OpenZeppelin/solidity-ast#31]
Hi,

Please there is an issue with the solidity-ast parser. 
When there is a smart contract containing ASCII art, the `src` generated by the solidity-ast is incorrect.
to reproduce this issue, you need to run solidity-ast on a file with ASCII art and a smart contract and then check the src of any node you want.

**Comment by frangio** [comment]
Are you referring to `srcDecoder`? Please provide the example code to reproduce.

**Comment by he110-1** [comment]
I really don't know if the srcDecoder has anything to do with this but here is an example of code that has this bug:

```typescript

for (const node of findAll("FunctionDefinition", file.ast)) {
  console.log(node.src)
}

```
if you take the `node.src` value and you try to convert it to a line number, the generated value will be wrong.

Here is an example of source code that can reproduce the issue
```solidity
// SPDX-License-Identifier: GPL-3.0

pragma solidity >=0.7.0 <0.9.0;

//  ______            _______ 
// (  ___ \ |\     /|(  ____ \
// | (   ) )| )   ( || (    \/
// | (__/ / | |   | || |      
// |  __ (  | |   | || | ____ 
// | (  \ \ | |   | || | \_  )
// | )___) )| (___) || (___) |
// |/ \___/ (_______)(_______)
//                            

/**
 * @title Owner
 * @dev Set & change owner
 */
contract Owner {

    address private owner;

    // event for EVM logging
    event OwnerSet(address indexed oldOwner, address indexed newOwner);

    // modifier to check if caller is owner
    modifier isOwner() {
        // If the first argument of 'require' evaluates to 'false', execution terminates and all
        // changes to the state and to Ether balances are reverted.
        // This used to consume all gas in old EVM versions, but not anymore.
        // It is often a good idea to use 'require' to check if functions are called correctly.
        // As a second argument, you can also provide an explanation about what went wrong.
        require(msg.sender == owner, "Caller is not owner");
        _;
    }

    /**
     * @dev Set contract deployer as owner
     */
    constructor() {
        owner = msg.sender; // 'msg.sender' is sender of current call, contract deployer for a constructor
        emit OwnerSet(address(0), owner);
    }

    /**
     * @dev Change owner
     * @param newOwner address of new owner
     */
    function changeOwner(address newOwner) public isOwner {
        emit OwnerSet(owner, newOwner);
        owner = newOwner;
    }

    /**
     * @dev Return owner address 
     * @return address of owner
     */
    function getOwner() external view returns (address) {
        return owner;
    }
} 


```

**Comment by frangio** [comment]
The `src` value is generated by solc, and this library doesn't change it in any way.

If you're trying to convert `src` into a line number, I recommend using the [`srcDecoder`](https://github.com/OpenZeppelin/solidity-ast#srcdecodersolcinput-solcoutput-basepath----node-node--string) utility.

I tried it against the example code you shared and got back correct line numbers for all FunctionDefinition nodes.

One thing you have to consider is that `src` is a byte index in the UTF8 encoded source code. Using it as a character index in JavaScript will result in discrepancies if the source code contains non-ASCII characters.
