### ISSUE TITLE
Invalid `subdenomination` field specification

### ISSUE THREAD

**Issue by PFAhard** [OpenZeppelin/solidity-ast#33]
The `subdenomination` field, as currently implemented, consistently returns a `null` value. This behavior is observed despite the field's intended functionality in Solidity, where it is used to specify ether units (such as `wei`, `gwei`, `ether`) and time units (`seconds`, `minutes`, `hours`, `days`, `weeks`).

**Comment by frangio** [comment]
Thanks! Now fixed in https://github.com/OpenZeppelin/solidity-ast/commit/01073d2cdea020e4403c485c26766f88b26db0cf and released in v0.4.54.
