### ISSUE TITLE
Add tooling to recompute functionSelector

### ISSUE THREAD

**Issue by Amxx** [OpenZeppelin/solidity-ast#7]
`functionSelector` is an optional field in `FunctionDefinition`. In fact, it was only added in solidity 0.6.0. This is a useful entry to have, and it could be helpful to have a 
```getFunctionSelector(node: FunctionDefinition): string)```
to help dealing with AST produced by solc 0.4 & 0.5

Given that `FunctionDefinition` includes the function name and function arguments, this should be too complex. It still, however, require recursive formatting of the parameters and adds a keccak256 dependency :/

**Comment by frangio** [comment]
It turns out that `functionSelector` is optional because not all kinds of functions have one. It's true that prior to 0.6 the field wasn't available, but this library is only compatible with >=0.6.

```typescript
function getFunctionSelector(fnDef: FunctionDefinition): string {
  assert(fnDef.kind === 'function' && ['external', 'public'].includes(fnDef.visibility));
  return fnDef.functionSelector!;
}
```
